---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aws-vpc
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: pauvilella.com/v1alpha1
    kind: VPC
  resources:
    - name: vpc
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            region: eu-west-1
            cidrBlock: 11.0.0.0/16
            enableDnsSupport: true
            enableDnsHostnames: true
    - name: subnet-a
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: eu-west-1a
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            region: eu-west-1
            availabilityZone: eu-west-1a
            cidrBlock: 11.0.0.0/24
            vpcIdSelector:
              matchControllerRef: true
    - name: subnet-b
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: eu-west-1b
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            region: eu-west-1
            availabilityZone: eu-west-1b
            cidrBlock: 11.0.1.0/24
            vpcIdSelector:
              matchControllerRef: true
    - name: subnet-c
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: eu-west-1c
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            region: eu-west-1
            availabilityZone: eu-west-1c
            cidrBlock: 11.0.2.0/24
            vpcIdSelector:
              matchControllerRef: true
    - name: gateway
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: InternetGateway
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            region: eu-west-1
            vpcIdSelector:
              matchControllerRef: true
    - name: routeTable
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTable
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            region: eu-west-1
            vpcIdSelector:
              matchControllerRef: true
    - name: route
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Route
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            region: eu-west-1
            routeTableIdSelector:
              matchControllerRef: true
            destinationCidrBlock: 0.0.0.0/0
            gatewayIdSelector:
              matchControllerRef: true
    - name: mainRouteTableAssociation
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: MainRouteTableAssociation
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            region: eu-west-1
            routeTableIdSelector:
              matchControllerRef: true
            vpcIdSelector:
              matchControllerRef: true
    - name: routeTableAssociation1a
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            region: eu-west-1
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
    - name: routeTableAssociation1b
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            region: eu-west-1
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
    - name: routeTableAssociation1c
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            region: eu-west-1
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
    - name: securityGroup
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            description: Security group description
            region: eu-west-1
            vpcIdSelector:
              matchControllerRef: true
