---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: my-subnet
spec:
  providerConfigRef:
    name: provider-aws
  forProvider:
    region: eu-west-1
    availabilityZone: eu-west-1a
    cidrBlock: 10.0.0.0/24
    vpcIdRef:
      name: my-vpc
    mapPublicIpOnLaunch: true
