---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: my-vpc
spec:
  providerConfigRef:
    name: provider-aws
  forProvider:
    region: eu-west-1
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
