---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aws-managed-resources
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: crossplane-provider-configs
  interval: 1m
  path: ./resources/aws-managed-resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
