---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-configurations
  namespace: flux-system
spec:
  dependsOn:
    - name: crossplane
  interval: 1m
  path: ./resources/crossplane-configurations
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
