---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-compositions
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: crossplane-provider-configs
  interval: 1m
  path: ./resources/crossplane-compositions
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
