---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
spec:
  interval: 1m
  releaseName: crossplane
  chart:
    spec:
      chart: crossplane
      version: 1.19
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
