---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - helm-release.yaml
  - helm.crossplane-provider.yaml
  - kubernetes.crossplane-provider.yaml
