---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: komoplane
spec:
  interval: 1m
  releaseName: komoplane
  chart:
    spec:
      chart: komoplane
      version: "0.1.6"
      sourceRef:
        kind: HelmRepository
        name: komodorio
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
      labels: {}
      hosts:
        - host: 127.0.0.1.nip.io
          paths:
            - path: /
              pathType: ImplementationSpecific
