---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
  - ingress-nginx-admission-create.job.yaml
  - ingress-nginx-admission-patch.job.yaml
  - ingress-nginx-admission.clusterrole.yaml
  - ingress-nginx-admission.clusterrolebinding.yaml
  - ingress-nginx-admission.role.yaml
  - ingress-nginx-admission.rolebinding.yaml
  - ingress-nginx-admission.serviceaccount.yaml
  - ingress-nginx-admission.validatingwebhookconfiguration.yaml
  - ingress-nginx-controller-admission.service.yaml
  - ingress-nginx-controller.deployment.yaml
  - ingress-nginx-controller.service.yaml
  - ingress-nginx.clusterrole.yaml
  - ingress-nginx.clusterrolebinding.yaml
  - ingress-nginx.configmap.yaml
  - ingress-nginx.role.yaml
  - ingress-nginx.rolebinding.yaml
  - ingress-nginx.serviceaccount.yaml
  - nginx.ingressclass.yaml
